services:
  postgres:
    image: postgres:15
    container_name: task-manager-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: mins4-123s-Fstk
      POSTGRES_DB: task-manager-db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local
